allowBuilds:
  esbuild: true
  sharp: false
  unrs-resolver: false
minimumReleaseAgeExclude:
  - '@supabase/auth-js@2.116.0'
  - '@supabase/functions-js@2.116.0'
  - '@supabase/postgrest-js@2.116.0'
  - '@supabase/realtime-js@2.116.0'
  - '@supabase/storage-js@2.116.0'
  - '@supabase/supabase-js@2.116.0'
  - '@types/node@26.5.0'
